config/routes.rb
Rails.application.routes.draw do
  get "login", to: "session#new", as: "login"
  post "session/new", to: "session#create", as: "login_create"
  post "logout", to: "session#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "user#index"
  resources :todos
  resources :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :due_date, presence: true

  def self.overdue
    all.where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where("completed = ?", true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method [:current_user]

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to todos_path
    else
      flash[:auth_error] = "Invalid Credentials"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
    # render plain: Todo.all.map { |todo| todo.to_pleasent_string }.join("\n")
    render "index"
  end

  def show
    todo = Todo.find(params[:id]).to_pleasent_string
    render plain: "#{todo}"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    id = current_user.id
    new_todo = Todo.new(todo_text: todo_text, due_date: due_date, completed: false, user_id: current_user.id)
    if new_todo.save
      redirect_to todos_path
    else
      flash[:todo_error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    new_status = params[:status]
    id = params[:id]
    todo = Todo.find(id)
    todo.completed = new_status
    todo.save
    redirect_to todos_path
    # render plain: "Todo with id : #{id} update as : Completed: #{new_status}"
  end

  def destroy
    id = params[:id]
    Todo.where("id = ?", id).destroy_all
    redirect_to todos_path
  end

  def authenticate
    if current_user
      return
    else
      redirect_to login_path
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    render "users/index"
  end

  def new
    render "users/new"
  end

  def create
    # Check for empty values
    new_user = User.new(name: params[:name], email: params[:email], password: params[:password])
    if new_user.save
      session[:user_id] = new_user.id
      redirect_to todos_path
    else
      flash[:auth_error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap' %>
    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/js/all.min.js" %>
  </body>
</html>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class="Homepage-wrapper">
  <h1>Welcome to Todo Manager <i class="far fa-list-alt todo-icon"></i></h1>

  <hr/>
  <div class="auth-form-wrapper">
    <h4 class="auth-title">LOGIN</h4>
    <div class="error-wrapper">
      <% if flash[:auth_error] %>
        <p class="todo-error">
          <%= flash[:auth_error] %>
        </p>
      <% end %>
    </div>
    <%= form_with url: login_create_path , method: :post do |form| %>
      <%= form.email_field :email, placeholder: "Email" %>
      <%= form.password_field :password, placeholder: "Password"%>
      <%= form.submit "Login!", class: "auth-button"%>
    <% end %>
  </div>
</div>

app/views/todos/_todo-section.html.erb
<section class="due">
  <h3><%= title%> <span class="remaining"><%= "#{todos.completed.length}/#{todos.length}"%></span></h3>
    <% todos.each do |todo|%>
      <div class="todo_wrapper">
        <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
          <input
            onclick="this.form.submit()"
            type="checkbox"
            name="status"
            class="checkbox_input"
            <%= todo.completed ? "checked": ""%>
          />
        <% end %>
        <span class="todo-text <%= todo.completed ? "striked": ""%>"><%= todo.todo_text %></span>
        <span class="overdue">
          <%=
            title == "Overdue" ? "Overdue" : ""
          %>
        </span>
        <span class="todo-due-date"><%= title == "Due Today" ? "" : todo.due_date.to_s(:short)%></span>
        <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
          <button class="delete-icon" onclick="this.form.submit()"><i class="far fa-trash-alt"></i></button>
        <% end %>
      </div>
    <%end%>
</section>

app/views/todos/index.html.erb
<body>
    <main>
      <section class="user-greetings">
        <% if current_user %>
          <p>Welcome <%= current_user.name%>!
          </p>
          <%= link_to "Logout", logout_path, method: :post %>
        <% end %>
      </section>
      <section class="title-block">
        <h1>My To-do List</h1>
        <% if flash[:todo_error] %>
          <p class="todo-error">
            <%= flash[:todo_error] %>
          </p>
        <% end %>
        <%= form_with(url: "/todos", method: "post", class: "add-todo-form") do%>
          <%= text_field_tag("todo_text",nil, placeholder: "What's next?")%>
          <%= hidden_field("user_id",current_user.id)%>
          <input type="date" name = "due_date">
            <i class="fas fa-calendar-week cal-icon"></i>
          </input>
          <button type="submit">Add</button>
        <% end %>
      </section>
      <%= render partial: "todo-section", locals: {
        title: "Overdue",
        todos: current_user.todos.overdue
      }%>
      <%= render partial: "todo-section", locals: {
        title: "Due Today",
        todos: current_user.todos.due_today
      }%>
      <%= render partial: "todo-section", locals: {
        title: "Due Later",
        todos: current_user.todos.due_later
      }%>
    </main>
  </body>

app/views/users/index.html.erb
<div class="Homepage-wrapper">
  <h1>Welcome to Todo Manager <i class="far fa-list-alt todo-icon"></i></h1>
  <hr/>
  <p>
    If you are a new User
    <%= link_to 'Click here', new_user_path %>
  </p>

  <p>
    If have an existing account
    <%= link_to "Click here", login_path %>
  </p>

</div>

app/views/users/new.html.erb
<div class="Homepage-wrapper">
  <h1>Welcome to Todo Manager <i class="far fa-list-alt todo-icon"></i></h1>

  <hr/>
  <div class="auth-form-wrapper">
    <h4 class="auth-title">SIGN UP</h4>
    <div class="error-wrapper">
      <% if flash[:auth_error] %>
        <p class="todo-error">
          <%= flash[:auth_error] %>
        </p>
      <% end %>
    </div>
    <%= form_with url: '/user', method: :post do |form| %>
      <%=form.text_field :name, placeholder: "Name" %>
      <%= form.email_field :email, placeholder: "Email" %>
      <%= form.password_field :password, placeholder: "Password"%>
      <%= form.submit "Sign-up!", class: "auth-button"%>
    <% end %>
  </div>
</div>